export const GET_COUNTRIES = "GET_COUNTRIES";

export const FILTER_CONTINENT = 'FILTER_CONTINENT';

export const ORDER_NAME = 'ORDER_NAME';

export const ORDER_POB = 'ORDER_POB';

export const POST_ACTIVITIE = 'POST_ACTIVITIE';

export const ACTIVITIES__SUCCESS= 'ACTIVITIES_SUCCESS';

export const ACTIVITIES__FAILURE= 'ACTIVITIES_FAILURE';